local ESX = exports["es_extended"]:getSharedObject()
RegisterCommand('tonefd', function(source, args, rawCommand)
    local playerPed = PlayerPedId()
    local coords = GetEntityCoords(playerPed)
    local streetHash, crossingHash = GetStreetNameAtCoord(coords.x, coords.y, coords.z)
    local streetName = GetStreetNameFromHashKey(streetHash)
    local message = table.concat(args, " ")
    TriggerServerEvent('dps_tone:requestTone', coords, streetName, message)
end)
RegisterNetEvent('dps_tone:playTone')
AddEventHandler('dps_tone:playTone', function(coords, location, message)
    PlaySoundFrontend(-1, "TIMER_STOP", "HUD_MINI_GAME_SOUNDSET", 1)
    Wait(800)
    PlaySoundFrontend(-1, "TIMER_STOP", "HUD_MINI_GAME_SOUNDSET", 1)
    Wait(800)
    PlaySoundFrontend(-1, "TIMER_STOP", "HUD_MINI_GAME_SOUNDSET", 1)
    SetNewWaypoint(coords.x, coords.y)
    ESX.ShowAdvancedNotification('DISPATCH', 'FIRE TONE OUT', 'Responding to: ' .. location .. (message or ""), 'CHAR_CALL911', 1)
end)
